In [1]:
import numpy as np

In [2]:
array = [1,2,3,4,5]
array += 1

TypeError: 'int' object is not iterable

In [9]:
array = np.array([1,2,3,4,5])
print(type(array))
array2 = array + 1
array2

<class 'numpy.ndarray'>


array([2, 3, 4, 5, 6])

In [7]:
array3 = array + array2
array3

array([ 3,  5,  7,  9, 11])

In [8]:
array.shape

(5,)

In [12]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])