In [1]:
import numpy as np

In [5]:
hao_array = np.array([[1.5, 1.3, 7.5],
                     [5.6, 7.8, 1.2]])
hao_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [6]:
np.sort(hao_array)  #default axis = -1

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [7]:
np.sort(hao_array, axis=0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [9]:
np.argsort(hao_array)  #原来的索引值

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [10]:
hao_array1 = np.linspace(0,10,10)
hao_array1

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
values = np.array([2.5, 6.5, 9.5])

In [14]:
np.searchsorted(hao_array1, values)  #对排序好的数组使用

array([3, 6, 9], dtype=int64)

In [15]:
hao_array2 = np.array([[1,0,6],
                     [1,7,0],
                     [2,3,1],
                     [2,4,0]])
hao_array2

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [22]:
index = np.lexsort([-1*hao_array2[:, 0], hao_array2[:, 2]])
index

array([3, 1, 2, 0], dtype=int64)

In [24]:
hao_array2 = hao_array2[index]
hao_array2

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])