数组形状操作

In [1]:
import numpy as np
hao_array = np.arange(10)
hao_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
hao_array.shape

(10,)

In [4]:
hao_array.shape = 2, 5

In [5]:
hao_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
hao_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
hao_array = np.arange(10)
hao_array.shape

(10,)

In [15]:
hao_array = hao_array[np.newaxis, :]
hao_array.shape

(1, 10)

In [16]:
hao_array = hao_array[:, np.newaxis]
hao_array.shape

(1, 1, 10)

In [17]:
hao_array = hao_array.squeeze()
hao_array.shape

(10,)

In [21]:
hao_array.shape = 2, 5
hao_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
hao_array00 = hao_array.transpose()
hao_array00

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [24]:
hao_array01 = hao_array.T
hao_array01

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

数组的连接

In [25]:
a = np.array([[123, 456, 789], [321, 654, 987]])
b = np.array([[111, 222, 333], [444, 555, 666]])

In [26]:
c = np.concatenate((a, b))
c

array([[123, 456, 789],
       [321, 654, 987],
       [111, 222, 333],
       [444, 555, 666]])

In [27]:
c1 = np.concatenate((a, b), axis=1)
c1

array([[123, 456, 789, 111, 222, 333],
       [321, 654, 987, 444, 555, 666]])

In [29]:
np.vstack((a, b))

array([[123, 456, 789],
       [321, 654, 987],
       [111, 222, 333],
       [444, 555, 666]])

In [30]:
np.hstack((a, b))

array([[123, 456, 789, 111, 222, 333],
       [321, 654, 987, 444, 555, 666]])

拉平

In [31]:
a

array([[123, 456, 789],
       [321, 654, 987]])

In [32]:
a.flatten()

array([123, 456, 789, 321, 654, 987])

In [33]:
a.reshape(1,6)

array([[123, 456, 789, 321, 654, 987]])

In [35]:
a.ravel()

array([123, 456, 789, 321, 654, 987])