array数组的数值计算

In [1]:
import numpy as np
hao_array = np.array([[1,2,3],[4,5,6]])
hao_array

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.sum(hao_array)

21

指定操作的额维度  加 乘

In [3]:
np.sum(hao_array, axis=0)

array([5, 7, 9])

In [4]:
hao_array.ndim

2

In [5]:
np.sum(hao_array, axis=1)

array([ 6, 15])

In [6]:
np.sum(hao_array, axis=-1)

array([ 6, 15])

In [7]:
hao_array.sum()

21

In [8]:
hao_array.sum(axis = 0)

array([5, 7, 9])

In [9]:
hao_array.sum(axis = 1)

array([ 6, 15])

In [10]:
hao_array.prod()

720

In [11]:
hao_array.prod(axis = 0)

array([ 4, 10, 18])

In [12]:
hao_array.prod(axis = 1)

array([  6, 120])

In [13]:
hao_array.min()

1

In [14]:
hao_array.min(axis = 0)

array([1, 2, 3])

In [15]:
hao_array.max(axis = 1)

array([3, 6])

找到索引位置

In [16]:
hao_array.argmax()

5

In [17]:
hao_array.argmin(axis = 0)

array([0, 0, 0])

In [18]:
hao_array.mean()

3.5

In [19]:
hao_array.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [23]:
np.median(hao_array, axis=0)

array([2.5, 3.5, 4.5])

标准差

In [23]:
hao_array.std()

1.707825127659933

In [24]:
hao_array.std(axis = 1)

array([0.81649658, 0.81649658])

方差

In [25]:
hao_array.var()

2.9166666666666665

In [26]:
hao_array.var(axis = 0)

array([2.25, 2.25, 2.25])

限制

In [27]:
hao_array.clip(2, 4)

array([[2, 2, 3],
       [4, 4, 4]])

四舍五入

In [28]:
yu_array = np.array([1.2, 3.4, 5.6])

In [29]:
yu_array.round()

array([1., 3., 6.])

In [30]:
yu_array.round(decimals = 1)

array([1.2, 3.4, 5.6])