随机模块

In [1]:
import numpy as np

In [36]:
np.random.rand(3,2)

array([[0.0820070976, 0.952036381 ],
       [0.6445647098, 0.3751995425],
       [0.6936137232, 0.2302468011]])

In [24]:
np.random.randint(0, 11, size=(5,4))

array([[7, 5, 3, 2],
       [3, 7, 8, 0],
       [6, 8, 5, 5],
       [8, 1, 2, 3],
       [6, 0, 4, 4]])

In [25]:
np.random.random_sample()

0.5678270544054959

In [26]:
np.random.randint(0, 10, 3)

array([4, 4, 6])

In [35]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([-0.0099307807,  0.0705861654, -0.0338680624, -0.1737589715,
       -0.2335570877, -0.0710901359, -0.2113186047, -0.0501441779,
        0.0281031067, -0.099074311 ])

In [38]:
np.set_printoptions(precision=3)

In [39]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.042, -0.073, -0.005, -0.127, -0.078,  0.006,  0.163,  0.024,
       -0.097, -0.113])

洗牌

In [42]:
hao_array = np.arange(10)
hao_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.random.shuffle(hao_array)
hao_array

array([0, 3, 5, 4, 9, 6, 2, 8, 7, 1])

随机种子

In [46]:
np.random.seed(0)

In [47]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])