In [1]:
import numpy as np

In [2]:
hao_list = [[1,2,3],[4,5,6],[7,8,9]]
hao_list1 = [[1,2,3],
            [4,5,6],
            [7,8,9]]
print(hao_list)
print('&&&&&&&&')
print(hao_list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
&&&&&&&&
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
hao_array = np.array(hao_list)
hao_array1 = np.array(hao_list1)
print(hao_array)
print('&&&&&&&')
print(hao_array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
&&&&&&&
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
hao_array.itemsize #itemsize表示每个元素所占的字节数

8

In [5]:
hao_array.size

9

In [6]:
hao_array.shape

(3, 3)

In [7]:
hao_array.ndim

2

In [8]:
hao_array.dtype

dtype('int64')

In [9]:
hao_array = np.arange(0,100,20)
hao_array

array([ 0, 20, 40, 60, 80])

In [10]:
mask = np.array([0,1,0,0,1], dtype=bool)
mask

array([False,  True, False, False,  True])

In [11]:
hao_array[mask]

array([20, 80])

In [15]:
array = np.array([[1,2,3],[4,5,6]])
array1 = array
array1[0,0] = 0
print(array)
print(array1)

[[0 2 3]
 [4 5 6]]
[[0 2 3]
 [4 5 6]]


In [16]:
array = np.array([[1,2,3],[4,5,6]])
array1 = array.copy()
array1[0,0] = 0
print(array)
print(array1)

[[1 2 3]
 [4 5 6]]
[[0 2 3]
 [4 5 6]]


In [29]:
np.random.rand(10)[np.random.rand(10)> 0.5]

array([0.80430318, 0.62209673, 0.75095233, 0.53168852])

In [30]:
mask = np.random.rand(10) > 0.5
print(mask, mask.dtype)

[ True False False False False False False False False False] bool


In [31]:
array = np.random.rand(10)
array[mask]

array([0.46376052])

In [32]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
mask = array > 5

In [36]:
array[mask]

array([6, 7, 8, 9])

In [37]:
np.where(mask)

(array([5, 6, 7, 8]),)

In [38]:
np.where(array > 5)

(array([5, 6, 7, 8]),)

In [40]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
array.dtype

dtype('int64')

In [42]:
array.itemsize

8

In [43]:
array.nbytes

72

In [44]:
array.size

9

In [48]:
size = array.nbytes/array.itemsize
print('size:{}, arraysize:{}'.format(size,array.size))

size:9.0, arraysize:9


In [49]:
sum_array = np.array([[1,2,3],[4,5,6]])
sum_array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.sum(sum_array)

21

In [51]:
np.sum(sum_array, axis=0)

array([5, 7, 9])

In [52]:
np.sum(sum_array, axis=1)

array([ 6, 15])

In [53]:
np.sum(sum_array, axis=-1)

array([ 6, 15])

In [54]:
pro_array = np.array([[1,2,3],[4,5,6]])
pro_array

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
pro_array.prod()

720

In [57]:
pro_array.prod(axis=0)

array([ 4, 10, 18])

In [58]:
pro_array.prod(axis=1)

array([  6, 120])

In [59]:
pro_array.prod(axis=-1)

array([  6, 120])

In [60]:
mm_array = np.array([[1,3,5,7,9],[2,4,6,8,10]])
mm_array

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [65]:
print(mm_array.min())
print(mm_array.min(axis=0))
print(mm_array.min(axis=1))

1
[1 3 5 7 9]
[1 2]


In [66]:
print(mm_array.max())
print(mm_array.max(axis=0))
print(mm_array.max(axis=1))

10
[ 2  4  6  8 10]
[ 9 10]


In [67]:
find_array = np.array([[1,2,3],[3,2,1],[4,5,6],[7,8,9]])
find_array

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
print(find_array.argmax())
print(find_array.argmax(axis=0))
print(find_array.argmax(axis=1))

11
[3 3 3]
[2 0 2 2]


In [71]:
print(find_array.argmin())
print(find_array.argmin(axis=0))
print(find_array.argmin(axis=1))

0
[0 0 1]
[0 2 0 0]


In [72]:
print(find_array.mean())
print(find_array.mean(axis=0))
print(find_array.mean(axis=1))

4.25
[3.75 4.25 4.75]
[2. 2. 5. 8.]


In [73]:
print(find_array.std())
print(find_array.std(axis=0))
print(find_array.std(axis=1))

2.6180463454008347
[2.16506351 2.48746859 3.03108891]
[0.81649658 0.81649658 0.81649658 0.81649658]


In [74]:
print(find_array.var())
print(find_array.var(axis=0))
print(find_array.var(axis=1))

6.854166666666667
[4.6875 6.1875 9.1875]
[0.66666667 0.66666667 0.66666667 0.66666667]


In [75]:
find_array.clip(2,7)

array([[2, 2, 3],
       [3, 2, 2],
       [4, 5, 6],
       [7, 7, 7]])

In [76]:
rd_array = np.array([[1.2,1.3,1.4,1.5],[1.5,1.6,1.7,1.8]])
rd_array

array([[1.2, 1.3, 1.4, 1.5],
       [1.5, 1.6, 1.7, 1.8]])

In [77]:
rd_array.round()

array([[1., 1., 1., 2.],
       [2., 2., 2., 2.]])

In [87]:
rd_array1 = np.array([[1.2345,1.3456,1.4567,1.5678],[1.5678,1.6789,1.7890,1.8900]])
rd_array1

array([[1.2345, 1.3456, 1.4567, 1.5678],
       [1.5678, 1.6789, 1.789 , 1.89  ]])

In [91]:
print(rd_array1.round())
print(rd_array1.round(decimals=1))
print(rd_array1.round(decimals=2))
print(rd_array1.round(decimals=4))

[[1. 1. 1. 2.]
 [2. 2. 2. 2.]]
[[1.2 1.3 1.5 1.6]
 [1.6 1.7 1.8 1.9]]
[[1.23 1.35 1.46 1.57]
 [1.57 1.68 1.79 1.89]]
[[1.2345 1.3456 1.4567 1.5678]
 [1.5678 1.6789 1.789  1.89  ]]


In [101]:
sort_array = np.array([[1,15,25,3,9],[9,56,4,18,15]])
sort_array

array([[ 1, 15, 25,  3,  9],
       [ 9, 56,  4, 18, 15]])

In [106]:
print(np.sort(sort_array))
print('&&&&&&&&&&&&&&&&&')
print(np.sort(sort_array, axis=0))
print('&&&&&&&&&&&&&&&&&')
print(np.sort(sort_array, axis=-1))  #default value: axis=-1

[[ 1  3  9 15 25]
 [ 4  9 15 18 56]]
&&&&&&&&&&&&&&&&&
[[ 1 15  4  3  9]
 [ 9 56 25 18 15]]
&&&&&&&&&&&&&&&&&
[[ 1  3  9 15 25]
 [ 4  9 15 18 56]]


In [107]:
sort_array.argsort()

array([[0, 3, 4, 1, 2],
       [2, 0, 4, 3, 1]])

In [122]:
search_array = np.arange(0,11,1)
search_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
values = np.array([1.5,3.5,9.5])
np.searchsorted(search_array, values)  #@@@@@@@@@@@@@@@@@@@@

array([ 2,  4, 10])

In [141]:
lexs_array = np.array([[1,3,1,7],[1,5,7,9],[3,2,3,4],[3,4,5,6]])
lexs_array

array([[1, 3, 1, 7],
       [1, 5, 7, 9],
       [3, 2, 3, 4],
       [3, 4, 5, 6]])

In [144]:
index = np.lexsort([-1*lexs_array[:,0]])
index

array([2, 3, 0, 1])

In [145]:
lexs_array[index]

array([[3, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 3, 1, 7],
       [1, 5, 7, 9]])

In [17]:
shape_array = np.arange(9)
shape_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
shape_array.shape

(9,)

In [24]:
shape_array = shape_array[np.newaxis, :]
shape_array

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])

In [25]:
shape_array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
shape_array = shape_array.reshape(3,3)[np.newaxis, :]
shape_array

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [29]:
shape_array.shape

(1, 3, 3)

In [30]:
shape_array.squeeze()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.squeeze(shape_array, axis=0).shape

(3, 3)

In [35]:
x = np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [36]:
np.squeeze(x, axis=0).shape

(3, 1)

In [37]:
np.squeeze(x, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [38]:
np.squeeze(x, axis=2).shape

(1, 3)

In [41]:
x0 = np.array([1234])

In [42]:
x1 = np.array([[1234]])

In [43]:
print(x0.shape, x1.shape)

(1,) (1, 1)


In [46]:
a = [1, 2, 3, 4, 5]
np.pad(a, (3, 3), 'constant', constant_values=(4, 6))

array([4, 4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [63]:
one678 = np.random.random((6,7,8))
one678[1,5,4] = 100
one678

array([[[7.22966207e-01, 4.28420511e-01, 8.95364625e-01, 2.74130789e-01,
         4.22551254e-01, 1.18494334e-01, 5.86938136e-01, 4.47567774e-01],
        [8.84632941e-01, 6.32337715e-01, 1.77885208e-01, 5.42339737e-01,
         9.98473389e-01, 4.41077552e-01, 3.56004471e-01, 3.96087192e-01],
        [4.23313136e-01, 1.02503210e-01, 3.84632789e-01, 1.75407701e-02,
         8.91580583e-01, 7.52730836e-01, 5.50516334e-01, 7.92347957e-01],
        [6.56040866e-01, 6.51280075e-01, 5.70631941e-02, 1.09978725e-01,
         8.04454067e-02, 9.78671696e-01, 2.87358261e-01, 3.01601448e-01],
        [5.65355204e-01, 6.05174882e-02, 2.36639858e-01, 7.08087317e-01,
         5.73801097e-01, 4.79331955e-01, 8.41865330e-01, 3.36079199e-01],
        [3.59312239e-01, 3.62161536e-01, 4.97218492e-01, 8.19344571e-01,
         8.24921851e-01, 9.96557822e-01, 2.42999259e-01, 7.02135311e-01],
        [6.89092536e-02, 5.77805984e-01, 7.74183655e-02, 8.08768669e-01,
         6.69497892e-01, 1.20538143e-02, 1.60