In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

构造数组

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.arange(2, 20, 2, dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [10]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

默认以10为底

In [11]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [16]:
print (help(np.logspace))

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [19]:
x = np.linspace(-10, 10, 5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [20]:
y = np.linspace(-10 , 10, 5)
y

array([-10.,  -5.,   0.,   5.,  10.])

网格

In [21]:
x, y = np.meshgrid(x, y)

In [22]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [23]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [24]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

常用功能

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3, 3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
x = np.empty(5)
x.shape

(5,)

In [35]:
x.fill(1)
x

array([1., 1., 1., 1., 1.])

In [38]:
hao_array = np.array([1, 2, 3, 4])
hao_array

array([1, 2, 3, 4])

In [39]:
np.zeros_like(hao_array)

array([0, 0, 0, 0])

In [40]:
np.ones_like(hao_array)

array([1, 1, 1, 1])

In [41]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])