In [1]:
import numpy as np

In [2]:
x = np.array([5, 5])
y = np.array([2, 2])

In [3]:
np.multiply(x, y)

array([10, 10])

In [4]:
np.dot(x, y)

20

In [5]:
x.shape = 2, 1

In [6]:
x

array([[5],
       [5]])

In [7]:
y.shape = 1, 2
y

array([[2, 2]])

In [8]:
np.dot(x, y)

array([[10, 10],
       [10, 10]])

In [10]:
x = np.array([1, 1, 1])
y = np.array([[1, 2, 3], [4, 5, 6]])
print(x * y)

[[1 2 3]
 [4 5 6]]


In [12]:
x = np.array([1, 1, 1])
y = np.array([[1, 2, 3]])
x == y

array([[ True, False, False]])

In [13]:
np.logical_and(x, y)

array([[ True,  True,  True]])

In [14]:
np.logical_or(x, y)

array([[ True,  True,  True]])

In [16]:
np.logical_not(x, y)

array([[0, 0, 0]])