读写

In [1]:
import numpy as np

In [2]:
%%writefile hao.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing hao.txt


In [4]:
data = []
with open('hao.txt') as f:
    for line in f:
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [5]:
data = np.loadtxt('hao.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [6]:
%%writefile hao1.txt
1,2,3,4,5,6
2,3,5,8,7,9

Writing hao1.txt


In [8]:
data = np.loadtxt('hao1.txt', delimiter=',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [9]:
%%writefile hao2.txt
x,y,z,w,a,b
1 2 3 4 5 6
2 3 5 8 7 9

Writing hao2.txt


In [10]:
data = np.loadtxt('hao2.txt', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

hao.txt：路径最好放到和代码一起
skiprows：去掉几行
delimiter：分隔符
usecols：指定使用哪几行

In [11]:
hao_array = np.array([[1,2,3],
                      [4,5,6]])


In [12]:
np.savetxt('hao3.txt', hao_array)

In [14]:
np.savetxt('hao3.txt', hao_array, fmt='%d')

In [15]:
np.savetxt('hao3.txt', hao_array, fmt='%d', delimiter=',')

In [16]:
np.savetxt('hao3.txt', hao_array, fmt='%.2f', delimiter=',')

读写array结构

In [18]:
hao_array = np.array([[1,2,3],
                      [4,5,6]])
np.save('hao_array.npy', hao_array)

In [21]:
hao = np.load('hao_array.npy')
hao

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
hao_array2 = np.arange(10)
hao_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.savez('hao.npz', a=hao_array, b=hao_array2)

In [46]:
data = np.load('hao.npz')

In [50]:
list(data.keys())

['a', 'b']

In [40]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])