In [1]:
import numpy as np

In [11]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [23]:
tang_list1 = [1,2,3,4,5.0]
tang_array1 = np.array(tang_list1)
tang_array1

array([1., 2., 3., 4., 5.])

基本属性

In [6]:
type(tang_array)
type(tang_array1)

numpy.ndarray

In [13]:
tang_array.dtype

dtype('int32')

In [14]:
tang_array1.dtype

dtype('float64')

In [15]:
tang_array.itemsize

4

In [16]:
tang_array.shape

(5,)

In [17]:
tang_array.size

5

In [19]:
np.shape(tang_array)

(5,)

In [20]:
tang_array.ndim

1

In [22]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

索引与切片

In [26]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[1]

2

In [27]:
tang_array[0:3]

array([1, 2, 3])

In [29]:
tang_array[:-1]

array([1, 2, 3, 4])

和Python相同

矩阵格式 多维度格式

In [30]:
tang_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
tang_array.shape

(3, 3)

In [32]:
tang_array.size

9

In [33]:
tang_array.ndim

2

In [34]:
tang_array[1,1] #按维度 一维 二维 三维 ...

5

In [35]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [36]:
tang_array[1]

array([ 4, 10,  6])

In [39]:
tang_array[:,1]

array([ 2, 10,  8])

In [40]:
tang_array[0,0:2]

array([1, 2])

In [41]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [42]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [50]:
tang_array3 = tang_array2.copy()
tang_array3

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [51]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [52]:
tang_array3[1,1] = 10000
tang_array3

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [44]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [53]:
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [54]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
mask = np.array([0,0,0,1,1,1,1,1,1,0], dtype=bool)
mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False])

In [57]:
tang_array[mask]

array([30, 40, 50, 60, 70, 80])

In [67]:
random_array = np.random.rand(10)
random_array

array([0.16460788, 0.96437795, 0.49678875, 0.20115017, 0.29469624,
       0.75621617, 0.03920527, 0.9369847 , 0.06857188, 0.49073016])

In [68]:
mask = random_array > 0.5
mask

array([False,  True, False, False, False,  True, False,  True, False,
       False])

In [69]:
tang_array[mask]

array([10, 50, 70])

In [70]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [ ]:
np.where