In [79]:
import numpy as np
import sys

In [8]:
print(np.__version__)

1.21.5


构造一个全零的矩阵，并打印其占用内存的大小

In [14]:
zs = np.zeros((5,5))
zs
print('%d bytes' %(zs.size * zs.itemsize))

200 bytes


打印一个函数的帮助文档，比如numpy.add

In [16]:
print(help(np.add))
# print(help(np.info(np.add)))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

创建一个10-49的数组，并将其倒序排列

In [19]:
ttfn = np.arange(10,50,1)
ttfn = ttfn[::-1]
ttfn

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组中不为0的索引

In [21]:
np.nonzero([1,2,3,4,5,0,2,0,3,0])

(array([0, 1, 2, 3, 4, 6, 8], dtype=int64),)

随机构造一个3*3的矩阵，并打印其中最大与最小值

In [50]:
tbt_array = np.random.random((3,3))
tbt_array
print("min:{} max:{}".format(tbt_array.min(),tbt_array.max()))

min:0.36962067919148867 max:0.9889910862903926


构造一个5*5的矩阵，令其值为1，并在最外层加上一圈0

In [52]:
os_array = np.ones((5,5))
os_array = np.pad(os_array, pad_width=1, mode='constant', constant_values=0)
os_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [53]:
print(help(np.pad))

Help on function pad in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
            Pads with the maximum value of all or part of

构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [55]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

对一个5*5的矩阵做归一化操作

In [60]:
hao_array = np.random.random((5,5))
hao_max = hao_array.max()
hao_min = hao_array.min()
hao_array = (hao_array - hao_min)/(hao_max - hao_min)
hao_array

array([[0.68231921, 0.53814802, 0.33212068, 0.08917249, 0.65340619],
       [0.10867184, 0.14961448, 0.59481098, 0.6131952 , 0.92664345],
       [0.37914142, 0.83074912, 0.49916664, 0.92268898, 0.74169545],
       [0.        , 0.58463227, 0.4193446 , 0.1813856 , 0.68914595],
       [0.16087985, 0.6293396 , 0.38372573, 0.0632002 , 1.        ]])

找到两个数组中相同的值

In [65]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1, z2)
print(np.intersect1d(z1,z2))

[8 2 0 0 1 6 4 0 7 3] [8 7 3 1 8 8 5 9 4 2]
[1 2 3 4 7 8]


得到今天 明天 昨天的日期

In [66]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-08-10 2022-08-11 2022-08-12


得到一个月的所有天

In [67]:
np.arange('2022-08','2022-09', dtype='datetime64[D]')

array(['2022-08-01', '2022-08-02', '2022-08-03', '2022-08-04',
       '2022-08-05', '2022-08-06', '2022-08-07', '2022-08-08',
       '2022-08-09', '2022-08-10', '2022-08-11', '2022-08-12',
       '2022-08-13', '2022-08-14', '2022-08-15', '2022-08-16',
       '2022-08-17', '2022-08-18', '2022-08-19', '2022-08-20',
       '2022-08-21', '2022-08-22', '2022-08-23', '2022-08-24',
       '2022-08-25', '2022-08-26', '2022-08-27', '2022-08-28',
       '2022-08-29', '2022-08-30', '2022-08-31'], dtype='datetime64[D]')

得到一个数的整数部分

In [69]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([2., 4., 6., 4., 0., 6., 0., 4., 6., 0.])

构造一个数组，让他不能被改变

In [73]:
z = np.zeros(5)
z.flags.writeable = False
z
z[0] = 1

ValueError: assignment destination is read-only

打印大量数据的部分值，全部值

In [74]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [81]:
np.set_printoptions(threshold=sys.maxsize)
z = np.zeros((15,15))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

在一个数组中，找到最接近一个数的索引

In [84]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z - v)).argmin()
print(z[index])

37.01369005773294
37


32位float类型和32位int类型转换

In [87]:
z = np.arange(10, dtype=np.int32)
print(z.dtype)
z = z.astype(np.float32)
print(z.dtype)

int32
float32


打印数组元素位置坐标与数值

In [88]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


按照数组的某一列进行排序

In [91]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[3 5 8]
 [6 2 7]
 [9 5 4]]
[[6 2 7]
 [3 5 8]
 [9 5 4]]


统计数组中每个数值出现的次数

In [92]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, 2, 1, 1, 0, 0, 1], dtype=int64)

如何对一个四维数组的最后两位来求和

In [101]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
print(z)
print("分隔********")
print(res)

[[[[0 9 6 0]
   [4 4 5 6]
   [5 4 9 1]
   [8 3 7 8]]

  [[9 4 1 3]
   [4 5 9 6]
   [5 6 7 5]
   [8 5 8 0]]

  [[3 3 7 3]
   [1 2 0 9]
   [7 7 5 4]
   [4 3 1 3]]

  [[4 1 6 3]
   [9 0 4 3]
   [9 5 1 6]
   [1 7 2 4]]]


 [[[6 7 1 1]
   [0 9 9 2]
   [4 8 9 3]
   [4 5 2 6]]

  [[3 7 2 0]
   [8 0 4 8]
   [6 3 1 9]
   [7 7 3 9]]

  [[9 1 9 3]
   [4 8 2 7]
   [2 8 9 9]
   [3 6 0 1]]

  [[4 8 6 8]
   [1 0 5 5]
   [1 8 5 9]
   [8 9 9 0]]]


 [[[4 5 2 6]
   [3 4 9 8]
   [2 9 2 0]
   [8 9 2 4]]

  [[9 5 7 5]
   [4 0 5 1]
   [0 3 3 0]
   [1 6 4 4]]

  [[7 9 2 3]
   [6 1 5 3]
   [2 3 6 3]
   [1 5 1 2]]

  [[2 0 6 3]
   [9 4 2 9]
   [0 4 2 4]
   [0 3 0 5]]]


 [[[4 8 4 7]
   [3 5 1 8]
   [0 5 0 9]
   [2 5 1 6]]

  [[7 3 8 7]
   [3 4 8 1]
   [7 6 5 6]
   [2 4 5 4]]

  [[7 9 5 0]
   [4 8 6 8]
   [2 9 7 1]
   [5 5 3 6]]

  [[4 0 9 2]
   [3 1 2 2]
   [2 7 9 9]
   [2 0 6 6]]]]
分隔********
[[79 85 62 65]
 [76 77 81 86]
 [77 57 59 53]
 [68 80 85 64]]


交换矩阵当中的两行

In [100]:
z = np.arange(25).reshape(5,5)
print(z)
print('xxxxx')
z[[0,1]] = z[[1,0]]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
xxxxx
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


找到一个数组当中最常出现的数字

In [102]:
z = np.random.randint(0,10,50)
print(np.bincount(z).argmax())

5


快速查找

In [103]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argpartition(-z,n)[:n]])

[9998 9999 9997 9996 9995]


去掉一个数组中，所有元素都相同的数据

In [114]:
z = np.random.randint(0,5,(10,3))
print(z)
e = np.all(z[:,1:] == z[:,:-1], axis=1)
print(e)

[False False False False False False False False  True False]


In [106]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(np.all(a==b))
print(np.any(a==b))

False
True
